// Generated by CoffeeScript 1.4.0
var index;

index = {
  init: function() {
    this.detectElements();
    return this.bindEvents();
  },
  detectElements: function() {
    return this.table = $("table");
  },
  bindEvents: function() {
    return this.initTable();
  },
  remove: function(id, el) {
    var _this = this;
    if (confirm("Remove this user?")) {
      return $.ajax({
        url: SYS.baseUrl + "admin/users/delete",
        type: "POST",
        dataType: "JSON",
        data: $.param({
          id: id
        }),
        success: function(res) {
          return _this.oTable.fnDeleteRow($(el).parents('tr')[0]);
        }
      });
    }
  },
  initTable: function() {
    return this.oTable = this.table.dataTable({
      sPaginationType: "bootstrap",
      bProcessing: true,
      bServerSide: true,
      iDisplayLength: 10,
      bRetrieve: true,
      sAjaxSource: SYS.baseUrl + "admin/apartments/getAjaxData"
    });
  }
};

$(document).ready(function() {
  return index.init();
});
