// Generated by CoffeeScript 1.4.0
var index;

index = {
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.modal = $('#myModal');
    return this.table = $("table");
  },
  bind_events: function() {
    return this.init_table();
  },
  reinit_stuff: function() {
    index.fin_delete_clicker();
    index.delete_clicker();
    return index.status_buttons_clicker();
  },
  delete_clicker: function() {
    var _this = this;
    this.delete_button = $('.delete');
    return this.delete_button.click(function(e) {
      var el;
      el = $(e.currentTarget);
      _this.fin_delete_btn.attr('data-id', el.data('id'));
      return _this.modal.modal();
    });
  },
  init_table: function() {
    return this.oTable = this.table.dataTable({
      sPaginationType: "bootstrap",
      bProcessing: true,
      bServerSide: true,
      iDisplayLength: 10,
      bRetrieve: true,
      sAjaxSource: SYS.baseUrl + "admin/apartments/getAjaxData",
      fnDrawCallback: index.reinit_stuff
    });
  },
  status_buttons_clicker: function() {
    var _this = this;
    this.status_buttons = $(".status");
    return this.status_buttons.click(function(e) {
      var el, text_status;
      el = $(e.currentTarget);
      text_status = el.html();
      return $.ajax({
        url: SYS.baseUrl + 'admin/apartments/change_status',
        data: $.param({
          id: el.data('id')
        }),
        type: 'POST',
        dataType: 'json',
        success: function(res) {
          if (res.text = "success") {
            if (text_status === "OK") {
              el.removeClass("label-success").addClass("label-important");
              return el.html("Pending");
            } else {
              el.removeClass("label-important").addClass("label-success");
              return el.html("OK");
            }
          }
        }
      });
    });
  },
  fin_delete_clicker: function() {
    var _this = this;
    this.fin_delete_btn = $('#final_delete');
    return this.fin_delete_btn.click(function(e) {
      var el;
      el = $(e.currentTarget);
      _this.modal.modal('hide');
      return $.ajax({
        url: SYS.baseUrl + 'admin/apartments/delete',
        data: $.param({
          id: el.data('id')
        }),
        type: 'POST',
        dataType: 'json',
        success: function(res) {
          if (res.text = "success") {
            return _this.oTable.fnDeleteRow($(el).parents('tr')[0]);
          }
        }
      });
    });
  }
};

$(document).ready(function() {
  return index.init();
});
