// Generated by CoffeeScript 1.4.0
var create;

create = {
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.geocomplete = $("#geocomplete");
    this.lat = $("input[name=lat]");
    this.lng = $("input[name=lng]");
    this.reset_button = $("#reset");
    return this.find_button = $("#find");
  },
  bind_events: function() {
    this.init_geocomplete();
    return this.find_press();
  },
  init_geocomplete: function() {
    return this.geocomplete.geocomplete({
      map: ".map_canvas"
    });
  },
  reset: function() {
    var _this = this;
    return this.reset_button.click(function() {
      _this.geocomplete.geocomplete("resetMarker");
      _this.reset_button.hide();
      return false;
    });
  },
  find_press: function() {
    var _this = this;
    return $("#find").click(function() {
      return _this.geocomplete.trigger("geocode");
    }).click();
  }
};

$(document).ready(function() {
  return create.init();
});
