// Generated by CoffeeScript 1.4.0
var index;

index = {
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.delete_button = $(".delete");
    this.modal = $('#myModal');
    this.title_modal = $('#title-modal');
    return this.fin_delete_btn = $('#final_delete');
  },
  bind_events: function() {
    this.delete_clicker();
    return this.fin_delete_clicker();
  },
  delete_clicker: function() {
    var _this = this;
    return this.delete_button.click(function(e) {
      var el;
      el = $(e.currentTarget);
      _this.title_modal.html($('.media#' + el.data('id') + ' .media-heading').html());
      _this.fin_delete_btn.attr('data-id', el.data('id'));
      return _this.modal.modal();
    });
  },
  fin_delete_clicker: function() {
    var _this = this;
    return this.fin_delete_btn.click(function(e) {
      var el;
      el = $(e.currentTarget);
      _this.modal.modal('hide');
      return $.ajax({
        url: SYS.baseUrl + 'apartments/delete',
        data: $.param({
          id: el.data('id')
        }),
        type: 'POST',
        dataType: 'json',
        success: function(res) {
          if (res.text = "success") {
            return $('.media#' + el.data('id')).remove();
          }
        }
      });
    });
  }
};

$(document).ready(function() {
  return index.init();
});
