// Generated by CoffeeScript 1.4.0
var user;

user = {
  init: function() {
    this.detectElements();
    return this.bindEvents();
  },
  detectElements: function() {
    return this.form = $('.form-actions');
  },
  bindEvents: function() {
    return this.initValidation();
  },
  initValidation: function() {
    return this.form.validate({
      rules: {
        name: {
          minlength: 2,
          required: true
        },
        email: {
          required: true,
          email: true
        },
        phone: {
          required: true,
          minlength: 6
        },
        cur_addr: {
          required: true,
          minlength: 6
        },
        cur_city_prov: {
          required: true,
          minlength: 6
        },
        cur_time: {
          required: true,
          minlength: 6
        },
        cur_post: {
          required: true,
          minlength: 5
        },
        source: {
          required: true,
          minlength: 6
        }
      },
      highlight: function(label) {
        return $(label).closest(".control-group").addClass("error");
      }
    });
  }
};

$(document).ready(function() {
  return user.init();
});
