// Generated by CoffeeScript 1.4.0
var contact;

contact = {
  init: function() {
    this.detectElements();
    return this.bindEvents();
  },
  detectElements: function() {
    return this.buttons = {
      request_callback: $('#request_callback'),
      send_secure_message: $('#send_secure_message')
    };
  },
  bindEvents: function() {
    var _this = this;
    return this.buttons.request_callback.on('click', function() {
      return _this.requestCallback();
    });
  },
  requestCallback: function(e) {
    var _this = this;
    return $.ajax({
      url: SYS.baseUrl + 'user/request_callback',
      dataType: 'json',
      beforeSend: function() {
        return $("#request-btn").addClass("disabled").removeAttr('data-toggle').attr('href', 'javscript:void(0)');
      },
      success: function(res) {
        return (new Alert).setLayout('main').setStatus('success').setMessage('Request was send').render();
      }
    });
  }
};

$(document).ready(function() {
  return contact.init();
});
