// Generated by CoffeeScript 1.4.0
var map;

map = {
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.map = document.getElementById("map_canvas");
    return this.map_options = {
      zoom: 8,
      center: new google.maps.LatLng(-34.397, 150.644),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
  },
  bind_events: function() {
    return this.initialize_map();
  },
  initialize_map: function() {
    var contentString, infowindow, marker;
    map = new google.maps.Map(this.map, this.map_options);
    contentString = "<div id=\"content\">Тут всё то про что должно быть рассказано</div>";
    infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(-34.397, 150.644),
      map: map,
      title: "Uluru (Ayers Rock)"
    });
    return google.maps.event.addListener(marker, "click", function() {
      return infowindow.open(map, marker);
    });
  }
};

$(document).ready(function() {
  return map.init();
});
