// Generated by CoffeeScript 1.4.0
var register;

register = {
  init: function() {
    this.detectElements();
    return this.bindEvents();
  },
  detectElements: function() {
    this.form = $('.form-actions');
    this.type_switcher = $("#type_switcher");
    return this.type = $("#type");
  },
  bindEvents: function() {
    this.initValidation();
    return this.init_type_switcher();
  },
  init_type_switcher: function() {
    var _this = this;
    return this.type_switcher.children().click(function(e) {
      var el;
      el = $(e.currentTarget);
      return _this.type.val(el.data("id"));
    });
  },
  initValidation: function() {
    return this.form.validate({
      rules: {
        first_name: {
          minlength: 2,
          required: true
        },
        last_name: {
          minlength: 2,
          required: true
        },
        email: {
          required: true,
          email: true
        },
        password: {
          minlength: 6,
          required: true
        }
      },
      highlight: function(label) {
        return $(label).closest(".control-group").addClass("error");
      },
      success: function(label) {
        return $(label).text("OK!").addClass("valid").closest(".control-group").addClass("success");
      }
    });
  }
};

$(document).ready(function() {
  return register.init();
});
